######################################
# Launch using ./run.sh
######################################
version: '2'
services:

  # mvn-305:
  #   image: maven:3.0.5-jdk-7
  #   container_name: mvn-305

  mvn-339:
    image: maven:3.3.9-jdk-7
    container_name: mvn-339

  gitflow-test:
    build:
      context: .
      args:
        - MAVEN_VERSION=3.3.9
        # - MAVEN_VERSION=3.0.5
        - GITFLOW_VERSION=3.0-SNAPSHOT
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_PASSWORD=${GITHUB_PASSWORD}
    container_name: gitflow-test
